spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: "jdbc:h2:mem:pricedb;DB_CLOSE_ON_EXIT=FALSE"
    driverClassName: org.h2.Driver
    username: user
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

